### ISSUE TITLE
Create a production ready way of bootstrapping users into the database

### ISSUE THREAD

**Issue by a-stacey** [data61/Mirza#269]
This definitely applies to the BR and probably to the SCS.

Specifically these users credentials should not be stored in the codebase and this is something that we need to work out before we can have a usable instance.

_Original Author: sta358_

_(Moved with github-migration-0.1.0.0 (package github-migration-0.1.0.0 revision df9f38b))_

**Comment by a-stacey** [comment]
Discussing with @snayler0 sounds like accepting as environment variables is the way to go.

**Comment by snayler0** [comment]
We should talk more about this... I hadn't fully understood the question, but re-reading here there might be some other ways to do it will catch up with you after lunch!

**Comment by a-stacey** [comment]
Ah cool great thanks.

**Comment by a-stacey** [comment]
We have decided that from the BR the plan will be to take the user / password via command line arguments, so something like:
```
stack exec -- businessRegistry bootstrap --user=username ---password=password --business=businessname
```
in this way CD can use it from the init container something like (detailed arguments omitted):
```
stack exec -- businessRegistry initdb && exit 0 & stack exec -- businessRegistry bootstrap
```

**Comment by a-stacey** [comment]
This feature should now be complete for the BusinessRegistry, the syntax is @snayler0:
```
stack exec -- businessRegistry bootstrap user password businessprefix 
```

**Comment by a-stacey** [comment]
Status Update: This is implemented and merged, just waiting for devops to add the config to the secrets and deploy for confirmation that it is resolved.
