### ISSUE TITLE
Healthz endpoint: Provide more info about service status

### ISSUE THREAD

**Issue by a-stacey** [data61/Mirza#299]
The aim is to give a bit more of an idea and report about the status of the service then the simple is it up required for load balancing. This can be used as diagnostics on production instances when issues arise.
Possibilities:
- Database status of the service (i.e. can the BR / SCS successfully communicate with the database and is it using the schema expected).
- Can the SCS communicate with the BR successfully?

These were issues raised by #291, but the implementation was just the MVP status for load balancing, but we might want to have these features by the time that we hit production proper. See discussion in #291 for further information.

_Original Author: sta358_

_(Moved with github-migration-0.1.0.0 (package github-migration-0.1.0.0 revision df9f38b))_

**Comment by paulsamways** [comment]
Returning 200 OK is a satisfactory health check for both the services at the moment.
