### ISSUE TITLE
BR: Add Optomised API Endpoint Needed For UX Front End

### ISSUE THREAD

**Issue by a-stacey** [data61/Mirza#340]
In todays meeting it was identified that we need to build an agregate endpoint to optomise the queries to the BR. So the Business registry front end API will be called by supply chain front end API so Cathy can get data all back in one call. Given company prefix return coordinates as well as address and UID for location.

The api inputs / outputs will look like:
List of GS1CompanyPrefixes -> Join of BusinessResponse + NewLocation

There will be a hard coded limit of the number of responses returned to limit abuse of say 10 businesses.

**Comment by a-stacey** [comment]
To complete this issue requires at least some of #364 to be fixed.

**Comment by ALL306** [comment]
@cathylill @a-stacey is still working on the Business registry front end API and @sajidanower23 has been blocked on the Supply chain front end API, he should move on to this today hopefully once another import issue is resolved. 

@a-stacey is there anything Cathy can review at this stage? Also think you mentioned yesterday you and @sajidanower23 were keen to get some more detail around requirements for data format.

**Comment by a-stacey** [comment]
@ALL306 This discussion really belongs in https://github.com/data61/Mirza/pull/369 as this is the feature that @cathylill needs to complete her implementation. That feature has a blocker on completion of this feature to be complete, but work on that issue should be able to be undertaken concurrently with this feature being completed. There is a PR https://github.com/data61/Mirza/pull/369 which addresses most of the underlying functionality that is required by #369 to appear complete for @cathylill, the only thing that is "functionally" missing from that PR is a business name is empty (there is a placeholder field which is empty where as when this feature is complete it will be populated). I now have a working commit in my local branch where this request resolves completely including the business name and should be able to PR this today if needed, otherwise there is still a little more work involved writing tests before I can do a final PR for this issue to be done-done, complete with tests, which hopefully should land either today or tomorrow (then there is the issue of getting #364, which I don't think should effect anything practically for @cathylill, but I'm not exactly sure and we can work through these problems if @cathylill notices them during testing at all).

**Comment by sajidanower23** [comment]
Considering it done since #376 has been merged.
