### ISSUE TITLE
Explicitly define the FromJSON/ToJSON instances

### ISSUE THREAD

**Issue by sajidanower23** [data61/Mirza#370]
It's important to do this so that the `ToJSON` instances in GS1Combinators are consistent with the `FromJSON` instances, so that events parsed by the library can be plugged into the server.

**Comment by ALL306** [comment]
From Paul (slack): I agree it should be a priority to make them at least complementary to each other, however as Ashley pointed out yesterday, don't worry too much about the field names. We'll fix those up when the epcis 2.0 spec comes out, we don't want to give the impression that we've started implementing that spec yet (gs1 was worried about us doing that and making it public)
