### ISSUE TITLE
Review SCI022 supply chain challenge phase 1 report to determine whether there are linkages to SCI041

### ISSUE THREAD

**Issue by ALL306** [data61/Mirza#457]
[Provenchain_info_C1P23_supply_chain_challenge_report_DS_Jan2019 (1).pdf](https://github.com/data61/Mirza/files/3225379/Provenchain_info_C1P23_supply_chain_challenge_report_DS_Jan2019.1.pdf)

**Comment by paulsamways** [comment]
https://confluence.csiro.au/display/blockchaintechnology/SCI022+Collaboration+-+Provenchain
